### ISSUE TITLE
demo url please

### ISSUE THREAD

**Issue by johnfelipe** [pudo/parltrack#22]
demo url please

**Comment by pudo** [comment]
http://parltrack.euwiki.org/

**Comment by johnfelipe** [comment]
All is with scrapers?, or is possible with admin interface

**Comment by pudo** [comment]
I think all the data is generated from scrapers, but @stef will know better.

**Comment by johnfelipe** [comment]
is possible create an instance for colombian councils?
Is possible translate to spanish, i can do it?

**Comment by stef** [comment]
makes no sense, every country has its own peculiarities. and they change constantly. good luck with your project.

**Comment by pudo** [comment]
It's worth pointing to the international [Poplus project](http://poplus.org/) which aims to build re-usable open source components for parliamentary tracking. If there's any chance you can, I would re-use some of their code - the guys at FCI in Chile are extra-awesome and will have prepared Spanish-language versions of everything.

**Comment by stef** [comment]
for republishing this makes a lot of sense, agreed. but unfortunately getting the data in any format is very much dependent on the data source - the parliament. i think the poplus formats are great for republishing, they are not very relevant in a ETL pipeline. Besides a html representation, an "API" that returns poplus formatted data can be quite useful indeed. Unfortunately parltrack has grown organically adapting to the changes and new data of the EU parliament, it is no beautiful generic framework like pudo deploys. I recommend you to look around his repos, you will find many much more inspiring frameworks and implementations, than in parltrack. However for various kinds of scrapers you can have a look at parltrack/parltrack/scrapers, where you can find scrapers for html, docs, and pdfs, among other things. for various transformations on the data you might want to have a look at parltrack/parltrack/filters/.
good luck again with you project.

**Comment by stef** [comment]
oh, i forgot to mention, you should also provide raw database dumps, if possible twice, one full dump, and one with poplus formats.
